name: Build and Push to GHCR, then Deploy to App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OWNER: your_github_user_or_org
  IMAGE: notion-rag
  TAG: latest
  WEBAPP_NAME: your-appservice-name

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # permite push a GHCR con GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.TAG }}
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.TAG }}
